first commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,44 +1,52 @@
-name: Deploy Flask with ngrok
+name: Deploy Flask App
 
 on:
   push:
     branches:
       - main
 
+env:
+  HEALTHCHECK_URL: http://34.228.255.233:50000
+
 jobs:
-  deploy:
-    runs-on: ubuntu-latest
+  Build-test-deploy:
+    runs-on: self-hosted
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
       - name: Set up Python
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v4
         with:
           python-version: '3.9'
 
-      - name: Install dependencies
+      - name: Virtual env
+        run: |
+          sudo apt install python3.12-venv -y
+          python3 -m venv venv
+          source venv/bin/activate
+          
+      - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Download ngrok
-        run: |
-          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
-          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
-          sudo apt update && sudo apt install ngrok
-
-      - name: Start ngrok tunnel
-        run: |
-          ngrok config add-authtoken 2bYI6e1UOLQu5wPReDZ4zxuGrPt_3zJfLy9wBFVWDfcAN58C6
-          nohup ngrok http 5000 > ngrok.log &
-          sleep 10
-
-      - name: Display ngrok URL
-        run: |
-          curl http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
-      
       - name: Run Gunicorn server
         run: |
           gunicorn app:app --bind 0.0.0.0:5000
+
+  health:
+    needs: Build-test-deploy
+    runs-on: self-hosted
+
+    steps:
+      - name: Health check
+        run: |
+          for i in {1..10}; do
+            curl -s -o /dev/null -w "%{http_code}" $HEALTHCHECK_URL | grep "200" && echo "Health check passed" && exit 0 || echo "Waiting for service...";
+            sleep 5;
+          done;
+          echo "Health check failed***" && exit 1
+          
+          
